name: CI

on:
  pull_request:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v4

      # Set up Ruby
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true  # Cache bundler dependencies

      # Install dependencies
      - name: Install dependencies
        run: |
          bundle install

      # Run RSpec tests
      - name: Run tests
        run: |
          bundle exec rspec prefix_evaluator_spec.rb
